{% set name = "censo" %}
{% set version = "2.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/CENSO/releases/download/v2.1.2/censo-2.1.2.tar.gz
  sha256: 3e031cd4d69f1ff9299b221d016ddd413c68b836b39400aa161e9e45ecdc8347

build:
  number: 0
  entry_points:
    - censo = censo.cli.interface:entry_point
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - xtb >=6.4.0

test:
  imports:
    - censo
    - censo.configuration
    - censo.ensembledata
    - censo.ensembleopt
    - censo.params
    - censo.properties
  commands:
    - pip check
    - censo --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/grimme-lab/censo
  summary: Commandline energetic sorting of conformer rotamer ensembles
  doc_url: https://xtb-docs.readthedocs.io/en/latest/CENSO_docs/censo.html
  license: GPL-3.0-or-later
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - awvwgk
    - fabothch
